version: 2.1
jobs:
  build:
    docker:
      - image: chef/inspec:4.18
    steps:
      - checkout
      - run:
          name: InSpec version
          command: |
            inspec version
      - run:
          name: Check profile
          command: |
            inspec check .